version: '3'
services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blabbr

  server:
    build: ./server
    ports:
      - '4000:4000'
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/server
      - /usr/src/server/node_modules
      - /Users/anshulsharma/projects/blabbr-sa.json:/usr/src/server/blabbr-sa.json:ro
    stdin_open: true
    tty: true
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/client
    env_file:
      - ./client/.env
    stdin_open: true
    tty: true
    depends_on:
      - server

volumes:
  postgres_data:
