version: '3'
services:
  server:
    build: ./server
    ports:
      - '4000:4000'
    env_file:
      - .env

    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
      - /Users/anshulsharma/projects/blabbr-sa.json:/usr/src/app/blabbr-sa.json:ro

  client:
    build: ./client
    ports:
      - '3000:80'
    depends_on:
      - server
